apiVersion: v1
kind: Service
metadata:
  name: db-host
  namespace: eshop
  labels:
    name: db-host
  annotations:
    omnideqname: eshop(app)->eshop(blueprint)->db-host(dep)->db-host(service)-clusterip(service-type)-service
spec:
  type: ClusterIP
  selector:
    app: db-host
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: db-host-port0
