apiVersion: v1
kind: Service
metadata:
  name: app-host
  namespace: eshop
  labels:
    name: app-host
  annotations:
    omnideqname: eshop(app)->eshop(blueprint)->app-host(dep)->app-host(service)-clusterip(service-type)-service
spec:
  type: ClusterIP
  selector:
    app: app-host
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: app-host-port0
