kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: eshop
  labels:
    name: test
  annotations:
    omnideqname: eshop(app)->eshop(blueprint)->test(dep)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      annotations: {}
    spec:
      containers: []
      volumes: []
      hostAliases: []
      imagePullSecrets: []
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 30
